baseURL = 'https://rizi97.github.io/talisman-hugo/'
languageCode = 'en'
title = 'Talisman'

[menu]
[[menu.main_menu]]
  identifier = 'home'
  name = 'Home'
  url = '/'
  weight = '1'
[[menu.main_menu]]
  identifier = 'about'
  name = 'About'
  url = '/about'
  weight = '2'
[[menu.main_menu]]
  identifier = 'resources'
  name = 'Resources'
  url = '/resources'
  weight = '3'
[[menu.main_menu]]
  identifier = 'sample-use'
  name = 'Sample Use'
  url = '/sample-use'
  weight = '4'
[[menu.main_menu]]
  identifier = 'contact'
  name = 'Contact'
  url = '/contact'
  weight = '5'


[Params]
siteLogo = "https://rizi97.github.io/talisman-hugo/assets/images/logo.png"
